# @package _global_

defaults:
  - ../task: HalfAdder
  - ../trainer: trainer
  - ../model: rnn_relu_Dale
  - _self_

  # OVERRIDES
  - override /model: rnn_tanh_Dale
#  - override /trainer: trainer_debug

display_figures: False
n_nets: 10

