# @package _global_

defaults:
  - ../task: MemoryAntiAngle
  - ../trainer: trainer
  - ../model: rnn_tanh
  - _self_

  # OVERRIDES
#  - override /model: rnn_tanh_Dale
#  - override /trainer: trainer_debug

display_figures: False
n_nets: 10
