# @package _global_

defaults:
  - ../task@task: MemoryNumber
  - ../trainer@trainer: trainer
  - ../model@model: rnn_relu_Dale
  - _self_

  # OVERRIDES
  - override ../model@model: rnn_relu_Dale
  - override ../task@task: MemoryNumber
  - override ../trainer@trainer: trainer

display_figures: False
n_nets: 1
