# @package task
taskname: "CDDM"
_target_: trainRNNbrain.tasks.Task${.taskname}.Task${.taskname}
T: 300
seed: null
T_cue_on: 0
T_cue_off: ${.T}
T_stim_on: '${eval:${.T}//3}'
T_stim_off: ${.T}
T_dec_on: '${eval:2*${.T}//3}'
T_dec_off: ${.T}
n_inputs: 6
n_outputs: 2
mask_params:
  - (${..T_cue_on}, ${..T_stim_on})
  - (${..T_dec_on}, ${..T_dec_off})
coherences: [-1.0, -0.5, -0.25, -0.125, -0.0625, -0.03125, -0.015625,
             0.0,
             0.015625, 0.03125, 0.0625, 0.125, 0.25, 0.5, 1.0]
task_params: ["n_steps",
              "n_inputs", "n_outputs",
              "cue_on", "cue_off", "stim_on", "stim_off", "dec_on", "dec_off",
              "coherences"]