# @package task
taskname: "NBitFlipFlop"
_target_: trainRNNbrain.tasks.Task${.taskname}.Task${.taskname}
T: 100
seed: null
mu_blocks: 10
T_min_block_length: 10
n_inputs: 3
n_outputs: 3
mu: 6
n_flip_steps: 10

mask_params:
  - (0, ${..T})